"""One-shot script to generate three count-based notebooks in the project root.

Run from anywhere:  python Leo/_build_count_notebooks.py
Then delete this script (or keep for re-runs).
"""
import json
import uuid
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent

def cell_md(src: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "source": src,
    }

def cell_code(src: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": uuid.uuid4().hex[:8],
        "metadata": {},
        "outputs": [],
        "source": src,
    }

def write_nb(path: Path, cells: list) -> None:
    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
    print(f"wrote {path}")


# ============================================================
# 1. KevinStructural-Leo.ipynb
# ============================================================
k_cells = [
    cell_md(
        "# Structural Networks — Weighted by Number of Synapses\n\n"
        "Two weighted directed graphs:\n"
        "1. **Full network** — all 906 coregistered, proofread neurons\n"
        "2. **Session 9.3 V1 network** — 93 V1 neurons from session 9, scan 3 (the "
        "session with the most V1 neurons in our matched set; all 99 neurons in that "
        "session are L4, 93 are in V1)\n\n"
        "**Weight = number of synapses (count of synaptic contacts between each pre→post "
        "pair).** Counterpart of `KevinStructural.ipynb` which uses cleft size in voxels; "
        "this version simply counts how many distinct synapses link each ordered pair. A "
        "pair with 5 contacts has weight 5."
    ),
    cell_code(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import networkx as nx\n"
        "import pickle\n"
        "import os\n"
        "from pathlib import Path\n\n"
        "import microns_datacleaner as mic\n"
        "import microns_datacleaner.filters as fl"
    ),
    cell_md("---\n## Part 1 — Load and Filter Neurons"),
    cell_code(
        "# Use the root data/ folder so we share raw files with the original notebooks.\n"
        "cleaner = mic.MicronsDataCleaner(datadir=\"data\", version=1718, download_policy='minimum')\n"
        "cleaner.tables['celltype'] = 'aibs_metamodel_celltypes_v661'\n"
        "units, _ = cleaner.process_nucleus_data(functional_data='best_only')\n\n"
        "proofread = fl.filter_neurons(units, proofread='ax_clean')\n"
        "matched   = fl.filter_neurons(proofread, tuning='matched').reset_index(drop=True)\n\n"
        "print(f\"Full working set: {len(matched)} neurons\")"
    ),
    cell_code(
        "# Session 9.3 V1 only: session=9, scan_idx=3, brain_area='V1'\n"
        "sess93_v1 = matched[\n"
        "    (matched['session']    == 9) &\n"
        "    (matched['scan_idx']   == 3) &\n"
        "    (matched['brain_area'] == 'V1')\n"
        "].reset_index(drop=True)\n\n"
        "print(f\"Session 9.3 V1 neurons: {len(sess93_v1)}\")\n"
        "print(f\"Layer breakdown:     {sess93_v1['layer'].value_counts().to_dict()}\")\n"
        "print(f\"Cell type breakdown: {sess93_v1['cell_type'].value_counts().to_dict()}\")"
    ),
    cell_md(
        "---\n## Part 2 — Load Synapses and Aggregate to Connection Counts\n\n"
        "The raw synapse table has one row per synaptic contact (pre → post). Multiple "
        "contacts can exist between the same ordered pair. To use **number of synapses** "
        "as the edge weight, we group by `(pre_pt_root_id, post_pt_root_id)` and count.\n\n"
        "We build two count tables:\n"
        "- **`syn_counts`** — all (pre, post) pairs among the 906 neurons (autapses removed)\n"
        "- **`syn_counts_93`** — only pairs where BOTH pre and post are in our 93-neuron V1 set"
    ),
    cell_code(
        "# Reuse synapses_matched.csv from root data/. The original KevinStructural.ipynb\n"
        "# builds this from connection_table_*.csv chunks; we read it directly.\n"
        "raw_synapses_path = Path('data/1718/raw/synapses_matched.csv')\n\n"
        "if not raw_synapses_path.exists():\n"
        "    # Build it from the chunks if needed.\n"
        "    synapse_dir = Path('data/1718/raw/synapses')\n"
        "    connection_files = sorted(\n"
        "        synapse_dir.glob('connections_table_*.csv'),\n"
        "        key=lambda p: int(p.stem.rsplit('_', 1)[1]),\n"
        "    )\n"
        "    if not connection_files:\n"
        "        raise FileNotFoundError(f'No connection tables found in {synapse_dir}')\n"
        "    pd.concat((pd.read_csv(p) for p in connection_files), ignore_index=True).to_csv(\n"
        "        raw_synapses_path, index=False\n"
        "    )\n\n"
        "synapses = pd.read_csv(raw_synapses_path)\n"
        "synapses = synapses[synapses['pre_pt_root_id'] != synapses['post_pt_root_id']].reset_index(drop=True)\n\n"
        "# 18-digit IDs are stored as float64 in CSVs — cast to int64 to match graph node keys.\n"
        "synapses['pre_pt_root_id']  = synapses['pre_pt_root_id'].astype('int64')\n"
        "synapses['post_pt_root_id'] = synapses['post_pt_root_id'].astype('int64')\n"
        "matched['pt_root_id']       = matched['pt_root_id'].astype('int64')\n"
        "sess93_v1 = matched[\n"
        "    (matched['session']    == 9) &\n"
        "    (matched['scan_idx']   == 3) &\n"
        "    (matched['brain_area'] == 'V1')\n"
        "].reset_index(drop=True)\n"
        "sess93_v1['pt_root_id'] = sess93_v1['pt_root_id'].astype('int64')\n\n"
        "# Aggregate to per-pair synapse counts (the new edge weight).\n"
        "syn_counts = (\n"
        "    synapses\n"
        "    .groupby(['pre_pt_root_id', 'post_pt_root_id'])\n"
        "    .size()\n"
        "    .reset_index(name='n_synapses')\n"
        ")\n\n"
        "print(f\"Raw synapse rows:           {len(synapses):,}\")\n"
        "print(f\"Unique (pre, post) pairs:   {len(syn_counts):,}\")\n"
        "print(f\"Synapses per pair — mean:   {syn_counts['n_synapses'].mean():.2f}\")\n"
        "print(f\"Synapses per pair — max:    {syn_counts['n_synapses'].max()}\")\n"
        "print(f\"Pairs with ≥2 synapses:      {(syn_counts['n_synapses']>=2).sum():,}\")\n"
        "print()\n\n"
        "ids_93 = set(sess93_v1['pt_root_id'].astype('int64').tolist())\n"
        "syn_counts_93 = syn_counts[\n"
        "    syn_counts['pre_pt_root_id'].isin(ids_93) &\n"
        "    syn_counts['post_pt_root_id'].isin(ids_93)\n"
        "].reset_index(drop=True)\n\n"
        "print(f\"Session 9.3 V1 (pre, post) pairs: {len(syn_counts_93):,}\")\n"
        "if len(syn_counts_93) > 0:\n"
        "    print(f\"Synapses per pair — mean:        {syn_counts_93['n_synapses'].mean():.2f}\")\n"
        "    print(f\"Synapses per pair — max:         {syn_counts_93['n_synapses'].max()}\")"
    ),
    cell_md(
        "---\n## Part 3 — Build Weighted Directed Graphs\n\n"
        "`nx.DiGraph` where:\n"
        "- **Nodes** carry attributes: `layer`, `cell_type`, `brain_area`, `pref_ori`, `gOSI`, "
        "spatial position\n"
        "- **Edges** carry `weight` = number of synapses between pre and post\n\n"
        "**Out-strength** = sum of synapse counts on outgoing edges = total outgoing synapses.\n"
        "**In-strength**  = sum of synapse counts on incoming edges = total incoming synapses."
    ),
    cell_code(
        "def build_count_digraph(neurons_df, syn_count_df):\n"
        "    G = nx.DiGraph()\n\n"
        "    node_ids    = neurons_df['pt_root_id'].astype('int64').tolist()\n"
        "    layers      = neurons_df['layer'].tolist()\n"
        "    cell_types  = neurons_df['cell_type'].tolist()\n"
        "    brain_areas = neurons_df['brain_area'].tolist()\n"
        "    pref_oris   = neurons_df['pref_ori'].tolist()\n"
        "    gOSIs       = neurons_df['gOSI'].tolist()\n"
        "    xs          = neurons_df['pt_position_x'].tolist()\n"
        "    ys          = neurons_df['pt_position_y'].tolist()\n"
        "    zs          = neurons_df['pt_position_z'].tolist()\n\n"
        "    for i, nid in enumerate(node_ids):\n"
        "        G.add_node(nid, layer=layers[i], cell_type=cell_types[i],\n"
        "                   brain_area=brain_areas[i], pref_ori=pref_oris[i],\n"
        "                   gOSI=gOSIs[i], x=xs[i], y=ys[i], z=zs[i])\n\n"
        "    node_set = set(G.nodes())\n"
        "    pre_ids  = syn_count_df['pre_pt_root_id'].astype('int64').tolist()\n"
        "    post_ids = syn_count_df['post_pt_root_id'].astype('int64').tolist()\n"
        "    counts   = syn_count_df['n_synapses'].tolist()\n\n"
        "    edges_added = 0\n"
        "    for pre, post, c in zip(pre_ids, post_ids, counts):\n"
        "        if pre in node_set and post in node_set:\n"
        "            G.add_edge(pre, post, weight=int(c))\n"
        "            edges_added += 1\n\n"
        "    print(f\"  Nodes: {G.number_of_nodes()}, edges added: {edges_added}\")\n"
        "    return G\n\n"
        "print('Building 906-neuron network...')\n"
        "G_906 = build_count_digraph(matched, syn_counts)\n\n"
        "if len(sess93_v1) == 0:\n"
        "    raise ValueError('sess93_v1 is empty. Re-run Part 1 cells before building G_93.')\n\n"
        "print('Building 93-neuron network...')\n"
        "G_93  = build_count_digraph(sess93_v1, syn_counts_93)\n"
        "if G_93.number_of_nodes() == 0:\n"
        "    raise ValueError('G_93 has 0 nodes. Re-run the sess93_v1 filtering cell first.')\n\n"
        "print()\n"
        "print(f\"Full 906-neuron network:     {G_906.number_of_nodes()} nodes, {G_906.number_of_edges():,} edges, density={nx.density(G_906):.4f}\")\n"
        "print(f\"Session 9.3 V1 network (93): {G_93.number_of_nodes()}  nodes, {G_93.number_of_edges():,} edges,  density={nx.density(G_93):.4f}\")"
    ),
    cell_md(
        "---\n## Part 4 — Degree and Strength Statistics\n\n"
        "**Degree** = number of distinct partners (unweighted).\n"
        "**Strength** = sum of synapse counts across all connections (weighted) "
        "= total number of synapses involving the neuron.\n\n"
        "Where the size-based version asks *how big are the synapses?*, here strength asks "
        "*how many synapses?*. A high-degree neuron with strength close to its degree forms "
        "mostly single-contact connections; high strength relative to degree signals "
        "multi-contact partnerships."
    ),
    cell_code(
        "def compute_stats(G, label):\n"
        "    if G.number_of_nodes() == 0:\n"
        "        raise ValueError(f'{label} has 0 nodes. Re-run the graph-building cell first.')\n"
        "    out_deg = np.array([d for _, d in G.out_degree()])\n"
        "    in_deg  = np.array([d for _, d in G.in_degree()])\n"
        "    out_str = np.array([d for _, d in G.out_degree(weight='weight')])\n"
        "    in_str  = np.array([d for _, d in G.in_degree(weight='weight')])\n"
        "    return out_deg, in_deg, out_str, in_str\n\n"
        "out_deg_906, in_deg_906, out_str_906, in_str_906 = compute_stats(G_906, 'G_906')\n"
        "out_deg_93,  in_deg_93,  out_str_93,  in_str_93  = compute_stats(G_93, 'G_93')\n\n"
        "def print_stats(label, out_deg, in_deg, out_str, in_str):\n"
        "    print(f\"\\n{'='*56}\")\n"
        "    print(f\" {label}\")\n"
        "    print(f\"{'='*56}\")\n"
        "    print(f\"  {'Metric':<35} {'Out':>9} {'In':>9}\")\n"
        "    print(f\"  {'-'*53}\")\n"
        "    print(f\"  {'Mean degree (partners)':<35} {out_deg.mean():>9.2f} {in_deg.mean():>9.2f}\")\n"
        "    print(f\"  {'Max degree':<35} {out_deg.max():>9} {in_deg.max():>9}\")\n"
        "    print(f\"  {'Neurons with degree 0':<35} {(out_deg==0).sum():>9} {(in_deg==0).sum():>9}\")\n"
        "    print(f\"  {'Mean strength (# synapses)':<35} {out_str.mean():>9.2f} {in_str.mean():>9.2f}\")\n"
        "    print(f\"  {'Max strength (# synapses)':<35} {out_str.max():>9} {in_str.max():>9}\")\n\n"
        "print_stats('Full 906-neuron Network',     out_deg_906, in_deg_906, out_str_906, in_str_906)\n"
        "print_stats('Session 9.3 V1 Network (93)', out_deg_93,  in_deg_93,  out_str_93,  in_str_93)"
    ),
    cell_md("---\n## Part 5 — Strength and Degree Distributions"),
    cell_code(
        "fig, axes = plt.subplots(2, 3, figsize=(18, 10))\n\n"
        "# Row 1: 906-neuron\n"
        "total_deg_906 = out_deg_906 + in_deg_906\n"
        "axes[0,0].hist(total_deg_906, bins=40, color='tomato', edgecolor='white', alpha=0.85)\n"
        "axes[0,0].axvline(total_deg_906.mean(), color='darkred', lw=2, linestyle='--',\n"
        "                  label=f'mean = {total_deg_906.mean():.1f}')\n"
        "axes[0,0].set_xlabel('Total Degree (in + out)')\n"
        "axes[0,0].set_ylabel('Count')\n"
        "axes[0,0].set_title('906-neuron: Degree Distribution')\n"
        "axes[0,0].legend()\n\n"
        "total_str_906 = out_str_906 + in_str_906\n"
        "axes[0,1].hist(total_str_906, bins=40, color='tomato', edgecolor='white', alpha=0.85)\n"
        "axes[0,1].axvline(total_str_906.mean(), color='darkred', lw=2, linestyle='--',\n"
        "                  label=f'mean = {total_str_906.mean():.1f}')\n"
        "axes[0,1].set_xlabel('Total Strength (# synapses, in + out)')\n"
        "axes[0,1].set_ylabel('Count')\n"
        "axes[0,1].set_title('906-neuron: Strength Distribution (synapse counts)')\n"
        "axes[0,1].legend()\n\n"
        "m = max(out_str_906.max(), in_str_906.max())\n"
        "axes[0,2].scatter(out_str_906, in_str_906, alpha=0.4, s=15, color='tomato')\n"
        "axes[0,2].plot([0, m], [0, m], 'k--', alpha=0.3, label='y = x')\n"
        "axes[0,2].set_xlabel('Out-strength (# outgoing synapses)')\n"
        "axes[0,2].set_ylabel('In-strength (# incoming synapses)')\n"
        "axes[0,2].set_title('906-neuron: Out vs In synapse counts')\n"
        "axes[0,2].legend()\n\n"
        "# Row 2: 93-neuron\n"
        "total_deg_93 = out_deg_93 + in_deg_93\n"
        "axes[1,0].hist(total_deg_93, bins=20, color='steelblue', edgecolor='white', alpha=0.85)\n"
        "axes[1,0].axvline(total_deg_93.mean(), color='navy', lw=2, linestyle='--',\n"
        "                  label=f'mean = {total_deg_93.mean():.1f}')\n"
        "axes[1,0].set_xlabel('Total Degree (in + out)')\n"
        "axes[1,0].set_ylabel('Count')\n"
        "axes[1,0].set_title('93-neuron (sess 9.3 V1): Degree Distribution')\n"
        "axes[1,0].legend()\n\n"
        "total_str_93 = out_str_93 + in_str_93\n"
        "axes[1,1].hist(total_str_93, bins=20, color='steelblue', edgecolor='white', alpha=0.85)\n"
        "axes[1,1].axvline(total_str_93.mean(), color='navy', lw=2, linestyle='--',\n"
        "                  label=f'mean = {total_str_93.mean():.1f}')\n"
        "axes[1,1].set_xlabel('Total Strength (# synapses, in + out)')\n"
        "axes[1,1].set_ylabel('Count')\n"
        "axes[1,1].set_title('93-neuron (sess 9.3 V1): Strength Distribution')\n"
        "axes[1,1].legend()\n\n"
        "if out_str_93.max() > 0:\n"
        "    m2 = max(out_str_93.max(), in_str_93.max())\n"
        "    axes[1,2].scatter(out_str_93, in_str_93, alpha=0.6, s=40, color='steelblue')\n"
        "    axes[1,2].plot([0, m2], [0, m2], 'k--', alpha=0.3, label='y = x')\n"
        "    axes[1,2].legend()\n"
        "axes[1,2].set_xlabel('Out-strength')\n"
        "axes[1,2].set_ylabel('In-strength')\n"
        "axes[1,2].set_title('93-neuron (sess 9.3 V1): Out vs In synapse counts')\n\n"
        "plt.suptitle('Structural Network — Degree and Strength (Synapse Count) Distributions',\n"
        "             fontsize=14, fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    cell_md(
        "---\n## Part 6 — Per-Pair Synapse Count Distribution\n\n"
        "Distribution of edge weights = how many synapses connect each (pre, post) pair. "
        "Most pairs have a single contact; a long right tail indicates the multi-contact "
        "partnerships that dominate total synapse count."
    ),
    cell_code(
        "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n"
        "counts_906 = syn_counts['n_synapses'].values\n"
        "max_count_906 = counts_906.max()\n"
        "bins_906 = np.arange(0.5, max_count_906 + 1.5, 1)\n"
        "axes[0].hist(counts_906, bins=bins_906, color='tomato', edgecolor='white', alpha=0.85)\n"
        "axes[0].axvline(np.median(counts_906), color='darkred', lw=2, linestyle='--',\n"
        "                label=f'median = {np.median(counts_906):.0f}')\n"
        "axes[0].axvline(counts_906.mean(), color='black', lw=1, linestyle=':',\n"
        "                label=f'mean = {counts_906.mean():.2f}')\n"
        "axes[0].set_xlabel('Synapses per (pre, post) pair')\n"
        "axes[0].set_ylabel('Count of pairs')\n"
        "axes[0].set_yscale('log')\n"
        "axes[0].set_title('906-neuron: Synapses per Pair (log y)')\n"
        "axes[0].legend()\n\n"
        "counts_93 = syn_counts_93['n_synapses'].values\n"
        "if len(counts_93) > 0:\n"
        "    bins_93 = np.arange(0.5, counts_93.max() + 1.5, 1)\n"
        "    axes[1].hist(counts_93, bins=bins_93, color='steelblue', edgecolor='white', alpha=0.85)\n"
        "    axes[1].axvline(np.median(counts_93), color='navy', lw=2, linestyle='--',\n"
        "                    label=f'median = {np.median(counts_93):.0f}')\n"
        "    axes[1].axvline(counts_93.mean(), color='black', lw=1, linestyle=':',\n"
        "                    label=f'mean = {counts_93.mean():.2f}')\n"
        "    axes[1].legend()\n"
        "axes[1].set_xlabel('Synapses per (pre, post) pair')\n"
        "axes[1].set_ylabel('Count of pairs')\n"
        "axes[1].set_title('93-neuron (sess 9.3 V1): Synapses per Pair')\n\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        "print(f'906-network — median: {np.median(counts_906):.0f}, mean: {counts_906.mean():.2f}, max: {counts_906.max()}, total synapses: {counts_906.sum():,}')\n"
        "if len(counts_93) > 0:\n"
        "    print(f'93-network  — median: {np.median(counts_93):.0f}, mean: {counts_93.mean():.2f}, max: {counts_93.max()}, total synapses: {counts_93.sum():,}')"
    ),
    cell_md(
        "---\n## Part 7 — Network Visualizations\n\n"
        "**93-neuron:** Spring layout, edge thickness and opacity proportional to synapse "
        "count (multi-contact pairs are visibly thicker).\n"
        "**906-neuron:** Actual x/z tissue coordinates. Node size ∝ total synapse count. "
        "Only multi-synapse edges drawn to reduce clutter."
    ),
    cell_code(
        "# 93-neuron: spring layout\n"
        "fig, ax = plt.subplots(figsize=(12, 10))\n\n"
        "np.random.seed(42)\n"
        "pos_93 = nx.spring_layout(G_93, weight='weight', seed=42, k=0.5)\n\n"
        "cell_types_93 = [G_93.nodes[n]['cell_type'] for n in G_93.nodes()]\n"
        "unique_types  = sorted(set(cell_types_93))\n"
        "cmap_nodes    = plt.cm.Set2(np.linspace(0, 1, max(len(unique_types), 1)))\n"
        "color_map     = {ct: cmap_nodes[i] for i, ct in enumerate(unique_types)}\n"
        "node_colors   = [color_map[ct] for ct in cell_types_93]\n\n"
        "edge_w_93 = np.array([G_93[u][v]['weight'] for u, v in G_93.edges()])\n"
        "if len(edge_w_93) > 0:\n"
        "    norm_w = (edge_w_93 - edge_w_93.min()) / (edge_w_93.max() - edge_w_93.min() + 1e-9)\n"
        "    widths = 0.4 + 3.5 * norm_w\n"
        "    alphas = 0.25 + 0.6 * norm_w\n"
        "    for (u, v), w, a in zip(G_93.edges(), widths, alphas):\n"
        "        nx.draw_networkx_edges(G_93, pos_93, edgelist=[(u, v)], width=float(w),\n"
        "                               alpha=float(a), edge_color='gray', arrows=True,\n"
        "                               arrowsize=10, connectionstyle='arc3,rad=0.1', ax=ax)\n\n"
        "nx.draw_networkx_nodes(G_93, pos_93, node_color=node_colors, node_size=150, ax=ax)\n"
        "nx.draw_networkx_labels(G_93, pos_93,\n"
        "                        labels={n: str(i) for i, n in enumerate(G_93.nodes())},\n"
        "                        font_size=5, ax=ax)\n"
        "for ct, c in color_map.items():\n"
        "    ax.scatter([], [], c=[c], s=80, label=ct)\n"
        "ax.legend(title='Cell type', loc='upper left', fontsize=8)\n"
        "ax.set_title(\n"
        "    f'Session 9.3 V1 Structural Network ({G_93.number_of_nodes()} neurons, {G_93.number_of_edges()} pairs)\\n'\n"
        "    f'Edge thickness ∝ # synapses per pair | All L4 neurons',\n"
        "    fontsize=12\n"
        ")\n"
        "ax.axis('off')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    cell_code(
        "# 906-neuron: spatial layout\n"
        "fig, ax = plt.subplots(figsize=(14, 10))\n\n"
        "pos_906       = {n: (G_906.nodes[n]['x'], G_906.nodes[n]['z']) for n in G_906.nodes()}\n"
        "area_colors   = {'V1': 'steelblue', 'RL': 'tomato', 'AL': 'gold', 'LM': 'green'}\n"
        "node_cols_906 = [area_colors.get(G_906.nodes[n]['brain_area'], 'gray') for n in G_906.nodes()]\n"
        "total_str_all = np.array([G_906.degree(n, weight='weight') for n in G_906.nodes()])\n"
        "node_sz       = 8 + 60 * (total_str_all / total_str_all.max())\n\n"
        "# Show pairs with at least 2 synapses (the multi-contact backbone).\n"
        "all_w_906   = np.array([G_906[u][v]['weight'] for u, v in G_906.edges()])\n"
        "heavy_edges = [(u, v) for u, v in G_906.edges() if G_906[u][v]['weight'] >= 2]\n\n"
        "nx.draw_networkx_edges(G_906, pos_906, edgelist=heavy_edges,\n"
        "                       alpha=0.08, width=0.5, edge_color='gray', arrows=False, ax=ax)\n"
        "nx.draw_networkx_nodes(G_906, pos_906, node_color=node_cols_906,\n"
        "                       node_size=node_sz, alpha=0.8, ax=ax)\n\n"
        "for area, color in area_colors.items():\n"
        "    ax.scatter([], [], c=color, s=60, label=area)\n"
        "ax.legend(title='Brain area', loc='upper right', fontsize=9)\n"
        "ax.set_title(\n"
        "    f'Full 906-neuron Structural Network — Spatial Layout\\n'\n"
        "    f'Node size ∝ total # synapses | Multi-synapse pairs shown ({len(heavy_edges):,}) | {G_906.number_of_edges():,} total pairs',\n"
        "    fontsize=12\n"
        ")\n"
        "ax.set_xlabel('x position (μm)')\n"
        "ax.set_ylabel('z position (μm)')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    cell_md("---\n## Part 8 — Summary Table"),
    cell_code(
        "summary = pd.DataFrame({\n"
        "    'Metric': [\n"
        "        'Nodes', 'Edges (pairs)', 'Network density',\n"
        "        'Mean out-degree', 'Mean in-degree', 'Max out-degree', 'Max in-degree',\n"
        "        'Mean out-strength (# synapses)', 'Mean in-strength (# synapses)',\n"
        "        'Max out-strength (# synapses)', 'Max in-strength (# synapses)',\n"
        "        'Median synapses per pair', 'Max synapses per pair',\n"
        "        'Total synapses', 'Neurons with zero output', 'Neurons with zero input',\n"
        "    ],\n"
        "    'Full 906-neuron': [\n"
        "        G_906.number_of_nodes(), G_906.number_of_edges(), f\"{nx.density(G_906):.4f}\",\n"
        "        f\"{out_deg_906.mean():.2f}\", f\"{in_deg_906.mean():.2f}\",\n"
        "        int(out_deg_906.max()), int(in_deg_906.max()),\n"
        "        f\"{out_str_906.mean():.2f}\", f\"{in_str_906.mean():.2f}\",\n"
        "        int(out_str_906.max()), int(in_str_906.max()),\n"
        "        f\"{np.median(counts_906):.0f}\", int(counts_906.max()),\n"
        "        int(counts_906.sum()),\n"
        "        int((out_deg_906 == 0).sum()), int((in_deg_906 == 0).sum()),\n"
        "    ],\n"
        "    'Session 9.3 V1 (93 neurons)': [\n"
        "        G_93.number_of_nodes(), G_93.number_of_edges(), f\"{nx.density(G_93):.4f}\",\n"
        "        f\"{out_deg_93.mean():.2f}\", f\"{in_deg_93.mean():.2f}\",\n"
        "        int(out_deg_93.max()), int(in_deg_93.max()),\n"
        "        f\"{out_str_93.mean():.2f}\", f\"{in_str_93.mean():.2f}\",\n"
        "        int(out_str_93.max()), int(in_str_93.max()),\n"
        "        f\"{np.median(counts_93):.0f}\" if len(counts_93) > 0 else 'N/A',\n"
        "        int(counts_93.max()) if len(counts_93) > 0 else 0,\n"
        "        int(counts_93.sum()) if len(counts_93) > 0 else 0,\n"
        "        int((out_deg_93 == 0).sum()), int((in_deg_93 == 0).sum()),\n"
        "    ]\n"
        "})\n\n"
        "print(summary.to_string(index=False))"
    ),
    cell_code(
        "# Save both graphs to data/. Suffix _count distinguishes them from the\n"
        "# size-based G_906.pkl / G_93.pkl produced by KevinStructural.ipynb.\n"
        "os.makedirs('data', exist_ok=True)\n\n"
        "with open('data/G_906_count.pkl', 'wb') as f:\n"
        "    pickle.dump(G_906, f)\n"
        "with open('data/G_93_count.pkl', 'wb') as f:\n"
        "    pickle.dump(G_93, f)\n\n"
        "print('Saved: data/G_906_count.pkl  and  data/G_93_count.pkl')\n"
        "print(\"Reload with:  G = pickle.load(open('data/G_906_count.pkl', 'rb'))\")"
    ),
]

write_nb(OUT / "KevinStructural-Leo.ipynb", k_cells)


# ============================================================
# 2. visualize_structural-Leo.ipynb
# ============================================================
v_cells = [
    cell_md(
        "# Structural Networks — Interactive 3D Visualization (Synapse Count)\n\n"
        "Loads pre-built NetworkX graphs (`data/G_906_count.pkl`, `data/G_93_count.pkl`) "
        "where edge weights are **number of synapses per pair** rather than synaptic cleft "
        "size. Renders interactive Plotly figures you can rotate, zoom, and hover.\n\n"
        "Also exports node and edge tables as CSV."
    ),
    cell_code(
        "import pickle\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import networkx as nx\n"
        "import plotly.graph_objects as go\n"
        "import plotly.express as px\n"
        "from plotly.subplots import make_subplots\n"
        "import os"
    ),
    cell_md("---\n## Load Graphs"),
    cell_code(
        "with open('data/G_906_count.pkl', 'rb') as f:\n"
        "    G_906 = pickle.load(f)\n"
        "with open('data/G_93_count.pkl', 'rb') as f:\n"
        "    G_93 = pickle.load(f)\n\n"
        "print(f'G_906: {G_906.number_of_nodes()} nodes, {G_906.number_of_edges():,} edges')\n"
        "print(f'G_93:  {G_93.number_of_nodes()} nodes,  {G_93.number_of_edges():,} edges')"
    ),
    cell_md("---\n## Plot Helper"),
    cell_code(
        "AREA_COL  = {'V1': '#4E79A7', 'RL': '#F28E2B', 'AL': '#59A14F',\n"
        "             'LM': '#E15759', 'unknown': '#aaaaaa'}\n"
        "LAYER_COL = {'L2/3': '#76B7B2', 'L4': '#EDC948', 'L5': '#B07AA1',\n"
        "             'L6': '#FF9DA7', 'unknown': '#aaaaaa'}\n\n"
        "def plot_3d(G, title, color_attr='brain_area', size_by='strength',\n"
        "            edge_pct_keep=50, dark=True):\n"
        "    # color_attr: 'brain_area' | 'layer' | 'pref_ori'\n"
        "    # size_by:    'strength' (total # synapses) | 'degree' (# partners)\n"
        "    # edge_pct_keep: keep top X% edges by weight (synapse count)\n"
        "    nodes = list(G.nodes())\n"
        "    xs = np.array([G.nodes[n]['x'] for n in nodes], dtype=float)\n"
        "    ys = np.array([G.nodes[n]['y'] for n in nodes], dtype=float)\n"
        "    zs = np.array([G.nodes[n]['z'] for n in nodes], dtype=float)\n\n"
        "    if size_by == 'strength':\n"
        "        raw = np.array([G.degree(n, weight='weight') for n in nodes], dtype=float)\n"
        "    else:\n"
        "        raw = np.array([G.degree(n) for n in nodes], dtype=float)\n"
        "    norm_sz = (raw - raw.min()) / (raw.max() - raw.min() + 1e-9)\n"
        "    sizes   = 4 + 16 * np.sqrt(norm_sz)\n\n"
        "    raw_attr = [G.nodes[n].get(color_attr) for n in nodes]\n"
        "    if color_attr == 'pref_ori':\n"
        "        cvals = np.array([float(v) if v is not None else 0.0 for v in raw_attr])\n"
        "        marker = dict(\n"
        "            size=sizes, color=cvals, colorscale='HSV', cmin=0, cmax=180,\n"
        "            colorbar=dict(title='Pref. ori. (deg)', thickness=14,\n"
        "                          tickvals=[0, 45, 90, 135, 180],\n"
        "                          tickfont=dict(color='white')),\n"
        "            line=dict(width=0.8, color='rgba(255,255,255,0.5)'),\n"
        "            opacity=0.92,\n"
        "        )\n"
        "        palette = {}\n"
        "    else:\n"
        "        palette = dict(AREA_COL if color_attr == 'brain_area' else LAYER_COL)\n"
        "        unique_vals = sorted(set(str(v) for v in raw_attr))\n"
        "        auto = px.colors.qualitative.Plotly\n"
        "        for i, v in enumerate(unique_vals):\n"
        "            if v not in palette:\n"
        "                palette[v] = auto[i % len(auto)]\n"
        "        col_list = [palette.get(str(v), '#aaaaaa') for v in raw_attr]\n"
        "        marker = dict(\n"
        "            size=sizes, color=col_list,\n"
        "            line=dict(width=0.8, color='rgba(255,255,255,0.5)'),\n"
        "            opacity=0.92,\n"
        "        )\n\n"
        "    hover = []\n"
        "    for n in nodes:\n"
        "        d   = G.nodes[n]\n"
        "        st  = G.degree(n, weight='weight')  # total # synapses\n"
        "        dg  = G.degree(n)                    # # partners\n"
        "        ori = d.get('pref_ori')\n"
        "        ori_s = f'{float(ori):.1f}' if ori is not None else 'N/A'\n"
        "        hover.append(\n"
        "            f'<b>Neuron {n}</b><br>'\n"
        "            f'Area: {d.get(\"brain_area\",\"?\")}  Layer: {d.get(\"layer\",\"?\")}'\n"
        "            f'  Type: {d.get(\"cell_type\",\"?\")}<br>'\n"
        "            f'Pref ori: {ori_s} deg  gOSI: {float(d.get(\"gOSI\",0)):.3f}<br>'\n"
        "            f'<b>Partners: {dg}   # Synapses: {st}</b>'\n"
        "        )\n\n"
        "    node_trace = go.Scatter3d(\n"
        "        x=xs, y=ys, z=zs, mode='markers',\n"
        "        marker=marker, text=hover, hoverinfo='text',\n"
        "        name='Neurons', showlegend=False,\n"
        "    )\n\n"
        "    legend_traces = []\n"
        "    if palette:\n"
        "        for val in sorted(palette):\n"
        "            legend_traces.append(go.Scatter3d(\n"
        "                x=[None], y=[None], z=[None], mode='markers',\n"
        "                marker=dict(size=10, color=palette[val]),\n"
        "                name=str(val), showlegend=True,\n"
        "            ))\n\n"
        "    all_edges = list(G.edges(data=True))\n"
        "    edge_traces = []\n"
        "    if all_edges:\n"
        "        ew = np.array([d['weight'] for _, _, d in all_edges], dtype=float)\n"
        "        threshold = np.percentile(ew, 100 - edge_pct_keep)\n"
        "        sel = [(u, v, d) for u, v, d in all_edges if d['weight'] >= threshold]\n"
        "        ew_sel  = np.array([d['weight'] for _, _, d in sel], dtype=float)\n"
        "        ew_norm = (ew_sel - ew_sel.min()) / (ew_sel.max() - ew_sel.min() + 1e-9)\n"
        "        N = 5\n"
        "        buckets = [[] for _ in range(N)]\n"
        "        for idx, (u, v, _) in enumerate(sel):\n"
        "            b = min(int(ew_norm[idx] * N), N - 1)\n"
        "            buckets[b].append((u, v))\n"
        "        for b, elist in enumerate(buckets):\n"
        "            if not elist:\n"
        "                continue\n"
        "            alpha = 0.05 + 0.25 * (b / (N - 1))\n"
        "            ex, ey, ez = [], [], []\n"
        "            for u, v in elist:\n"
        "                ex += [G.nodes[u]['x'], G.nodes[v]['x'], None]\n"
        "                ey += [G.nodes[u]['y'], G.nodes[v]['y'], None]\n"
        "                ez += [G.nodes[u]['z'], G.nodes[v]['z'], None]\n"
        "            edge_traces.append(go.Scatter3d(\n"
        "                x=ex, y=ey, z=ez, mode='lines',\n"
        "                line=dict(color=f'rgba(180,180,220,{alpha:.2f})', width=1),\n"
        "                hoverinfo='none',\n"
        "                showlegend=(b == N - 1),\n"
        "                name=f'Pairs ({len(sel):,} shown)',\n"
        "            ))\n\n"
        "    bg   = '#0e0e12' if dark else 'white'\n"
        "    axcol= '#888888' if dark else '#333'\n"
        "    tcol = 'white'   if dark else 'black'\n\n"
        "    fig = go.Figure(data=edge_traces + legend_traces + [node_trace])\n"
        "    fig.update_layout(\n"
        "        title=dict(text=title, x=0.5,\n"
        "                   font=dict(size=19, color=tcol, family='Arial')),\n"
        "        paper_bgcolor=bg,\n"
        "        scene=dict(\n"
        "            bgcolor=bg,\n"
        "            xaxis=dict(title='x (nm)', showgrid=False, zeroline=False,\n"
        "                       color=axcol, showbackground=False),\n"
        "            yaxis=dict(title='y (nm)', showgrid=False, zeroline=False,\n"
        "                       color=axcol, showbackground=False),\n"
        "            zaxis=dict(title='z (nm)', showgrid=False, zeroline=False,\n"
        "                       color=axcol, showbackground=False),\n"
        "            camera=dict(eye=dict(x=1.4, y=1.4, z=0.8)),\n"
        "        ),\n"
        "        legend=dict(\n"
        "            font=dict(color=tcol, size=12),\n"
        "            bgcolor='rgba(0,0,0,0.35)',\n"
        "            bordercolor='#444', borderwidth=1,\n"
        "            itemsizing='constant',\n"
        "        ),\n"
        "        margin=dict(l=0, r=0, b=0, t=60),\n"
        "        height=720,\n"
        "    )\n"
        "    return fig"
    ),
    cell_md(
        "---\n## Full 906-Neuron Network\n\n"
        "Colour = **brain area** (V1 / RL / AL / LM).\n"
        "Node size ∝ total **number of synapses** (in + out).\n"
        "Top 50% of pairs by synapse count drawn; brighter = more synapses."
    ),
    cell_code(
        "fig_906 = plot_3d(\n"
        "    G_906,\n"
        "    title='Full 906-Neuron Network (synapse counts)  |  Colour: Brain Area',\n"
        "    color_attr='brain_area',\n"
        "    size_by='strength',\n"
        "    edge_pct_keep=50,\n"
        ")\n"
        "fig_906.show()"
    ),
    cell_md("Same network coloured by **cortical layer**, sized by **degree** (number of partners)."),
    cell_code(
        "fig_906_layer = plot_3d(\n"
        "    G_906,\n"
        "    title='Full 906-Neuron Network (synapse counts)  |  Colour: Cortical Layer',\n"
        "    color_attr='layer',\n"
        "    size_by='degree',\n"
        "    edge_pct_keep=30,\n"
        ")\n"
        "fig_906_layer.show()"
    ),
    cell_md(
        "---\n## Session 9.3 V1 Subnetwork (93 Neurons)\n\n"
        "All neurons are L4 in V1, so area/layer give no contrast.\n"
        "Colour = **preferred orientation** (cyclic HSV, 0°–180°).\n"
        "All pairs shown; edge brightness ∝ # synapses per pair."
    ),
    cell_code(
        "fig_93 = plot_3d(\n"
        "    G_93,\n"
        "    title='Session 9.3 V1 Network (synapse counts)  |  Colour: Preferred Orientation',\n"
        "    color_attr='pref_ori',\n"
        "    size_by='degree',\n"
        "    edge_pct_keep=100,\n"
        ")\n"
        "fig_93.show()"
    ),
    cell_md("Same 93-neuron network, sized by **strength** (total # synapses), coloured by area."),
    cell_code(
        "fig_93b = plot_3d(\n"
        "    G_93,\n"
        "    title='Session 9.3 V1 Network (synapse counts)  |  Colour: Brain Area  |  Size: Strength',\n"
        "    color_attr='brain_area',\n"
        "    size_by='strength',\n"
        "    edge_pct_keep=100,\n"
        ")\n"
        "fig_93b.show()"
    ),
    cell_md(
        "---\n## Export Node and Edge Tables as CSV\n\n"
        "Saves to `data/exports/`. One node CSV and one edge CSV per network. "
        "Edge weights are `n_synapses` (count per pair)."
    ),
    cell_code(
        "os.makedirs('data/exports', exist_ok=True)\n\n"
        "def export_graph(G, prefix):\n"
        "    rows = []\n"
        "    for n in G.nodes():\n"
        "        d = G.nodes[n]\n"
        "        rows.append({\n"
        "            'neuron_id':    n,\n"
        "            'brain_area':   d.get('brain_area'),\n"
        "            'layer':        d.get('layer'),\n"
        "            'cell_type':    d.get('cell_type'),\n"
        "            'pref_ori':     d.get('pref_ori'),\n"
        "            'gOSI':         d.get('gOSI'),\n"
        "            'x':            d.get('x'),\n"
        "            'y':            d.get('y'),\n"
        "            'z':            d.get('z'),\n"
        "            'out_degree':   G.out_degree(n),\n"
        "            'in_degree':    G.in_degree(n),\n"
        "            'out_strength': G.out_degree(n, weight='weight'),\n"
        "            'in_strength':  G.in_degree(n, weight='weight'),\n"
        "        })\n"
        "    nodes_df = pd.DataFrame(rows)\n"
        "    nodes_df.to_csv(f'data/exports/{prefix}_nodes.csv', index=False)\n"
        "    print(f'Saved data/exports/{prefix}_nodes.csv  ({len(nodes_df)} rows)')\n\n"
        "    edges = [(u, v, G[u][v]['weight']) for u, v in G.edges()]\n"
        "    edges_df = pd.DataFrame(edges,\n"
        "                             columns=['pre_neuron_id', 'post_neuron_id', 'n_synapses'])\n"
        "    edges_df.to_csv(f'data/exports/{prefix}_edges.csv', index=False)\n"
        "    print(f'Saved data/exports/{prefix}_edges.csv  ({len(edges_df)} rows)')\n\n"
        "export_graph(G_906, 'G_906_count')\n"
        "export_graph(G_93,  'G_93_count')"
    ),
    cell_md("---\n## Quick Stats Recap"),
    cell_code(
        "for label, G in [('906-neuron', G_906), ('93-neuron (sess 9.3 V1)', G_93)]:\n"
        "    od  = np.array([d for _, d in G.out_degree()])\n"
        "    id_ = np.array([d for _, d in G.in_degree()])\n"
        "    os_ = np.array([d for _, d in G.out_degree(weight='weight')])\n"
        "    is_ = np.array([d for _, d in G.in_degree(weight='weight')])\n"
        "    print(f\"{'='*52}\")\n"
        "    print(f' {label}')\n"
        "    print(f\"{'='*52}\")\n"
        "    print(f'  Nodes:          {G.number_of_nodes()}')\n"
        "    print(f'  Edges (pairs):  {G.number_of_edges():,}')\n"
        "    print(f'  Density:        {nx.density(G):.4f}')\n"
        "    print(f'  Mean out-deg:   {od.mean():.2f}   Max: {od.max()}')\n"
        "    print(f'  Mean in-deg:    {id_.mean():.2f}   Max: {id_.max()}')\n"
        "    print(f'  Mean out-strength (# syn): {os_.mean():.2f}   Max: {os_.max()}')\n"
        "    print(f'  Mean in-strength (# syn):  {is_.mean():.2f}   Max: {is_.max()}')\n"
        "    print()"
    ),
]

write_nb(OUT / "visualize_structural-Leo.ipynb", v_cells)


# ============================================================
# 3. compare_structural_functional-Leo.ipynb
# ============================================================
c_cells = [
    cell_md(
        "# Structure vs Function — Network Comparison (Synapse Count)\n\n"
        "Compares the **functional network** (93×93 Pearson correlation matrix, session 9.3 "
        "V1) with the **count-weighted structural network** (same 93 neurons; edge weight = "
        "number of synapses per pair).\n\n"
        "Counterpart of `compare_structural_functional.ipynb` which uses synaptic cleft size "
        "as edge weight; this version uses synapse count instead.\n\n"
        "Key questions:\n"
        "- Are directly connected neurons more functionally correlated?\n"
        "- Does the **number of synapses** between two neurons predict functional similarity?\n"
        "- Do connected neurons share orientation tuning preferences?\n"
        "- Are hub neurons in the structural network also hubs functionally?\n"
        "- Do both networks share the same topology?"
    ),
    cell_code(
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "import matplotlib.gridspec as gridspec\n"
        "import seaborn as sns\n"
        "from scipy import stats\n"
        "import networkx as nx\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n\n"
        "plt.rcParams.update({'figure.dpi': 110, 'font.size': 11,\n"
        "                     'axes.spines.top': False, 'axes.spines.right': False})\n"
        "print('Libraries loaded.')"
    ),
    cell_md("---\n## 1. Load Data"),
    cell_code(
        "# Functional matrix lives in the root outputs/ folder.\n"
        "F           = np.load('outputs/functional_network/F_correlation_matrix.npy')\n"
        "func_cohort = pd.read_csv('outputs/functional_network/functional_cohort.csv')\n\n"
        "# Count-weighted structural exports (created by visualize_structural-Leo.ipynb).\n"
        "s_nodes = pd.read_csv('data/exports/G_93_count_nodes.csv')\n"
        "s_edges = pd.read_csv('data/exports/G_93_count_edges.csv')\n\n"
        "s_nodes_906 = pd.read_csv('data/exports/G_906_count_nodes.csv')\n"
        "s_edges_906 = pd.read_csv('data/exports/G_906_count_edges.csv')\n\n"
        "print(f'Functional matrix shape : {F.shape}')\n"
        "print(f'Functional cohort       : {func_cohort.shape}')\n"
        "print(f'Structural nodes (93)   : {s_nodes.shape}')\n"
        "print(f'Structural edges (93)   : {s_edges.shape}')\n"
        "print(f'Structural nodes (906)  : {s_nodes_906.shape}')\n"
        "print(f'Structural edges (906)  : {s_edges_906.shape}')\n"
        "print(f'\\nF diagonal (should all be 1.0): {np.unique(np.diag(F))}')"
    ),
    cell_md("---\n## 2. Merge Structural + Functional into One Table"),
    cell_code(
        "merged = func_cohort.merge(\n"
        "    s_nodes[['neuron_id', 'pref_ori', 'gOSI',\n"
        "             'out_degree', 'in_degree', 'out_strength', 'in_strength']],\n"
        "    left_on='pt_root_id', right_on='neuron_id',\n"
        "    how='inner'\n"
        ").reset_index(drop=True)\n\n"
        "print(f'Merged table: {merged.shape} rows x cols')\n"
        "print(f'Columns: {merged.columns.tolist()}')\n"
        "assert len(merged) == 93, 'Expected 93 neurons after merge!'\n\n"
        "id2midx = dict(zip(merged['pt_root_id'], merged['matrix_index']))\n\n"
        "s_edges['pre_neuron_id']  = s_edges['pre_neuron_id'].astype('int64')\n"
        "s_edges['post_neuron_id'] = s_edges['post_neuron_id'].astype('int64')\n"
        "conn_set = set(zip(s_edges['pre_neuron_id'], s_edges['post_neuron_id']))\n"
        "print(f'Structural connected pairs (directed): {len(conn_set)}')"
    ),
    cell_md(
        "---\n## 3. Build All-Pairs Table\n\n"
        "For every unordered pair of neurons (i, j) compute:\n"
        "- `f_corr` — Pearson correlation from the functional matrix\n"
        "- `conn_type` — `none` / `unidirectional` / `bidirectional`\n"
        "- `n_synapses` — max synapse count between i→j and j→i (NaN if neither direction connects)\n"
        "- `total_synapses` — sum of synapse counts in both directions\n"
        "- `dist_um` — 3-D Euclidean distance in µm\n"
        "- `ori_sim` — orientation tuning similarity cos(2·Δθ)"
    ),
    cell_code(
        "neurons = merged['pt_root_id'].values.astype('int64')\n"
        "midxs   = merged['matrix_index'].values\n"
        "xs = merged['pt_position_x'].values\n"
        "ys = merged['pt_position_y'].values\n"
        "zs = merged['pt_position_z'].values\n"
        "thetas = merged['pref_ori'].values\n\n"
        "# (pre, post) -> n_synapses\n"
        "syn_n = dict(zip(zip(s_edges['pre_neuron_id'], s_edges['post_neuron_id']),\n"
        "                 s_edges['n_synapses']))\n\n"
        "rows = []\n"
        "n = len(neurons)\n"
        "for i in range(n):\n"
        "    for j in range(i + 1, n):\n"
        "        ni, nj = int(neurons[i]), int(neurons[j])\n"
        "        fij = float(F[midxs[i], midxs[j]])\n"
        "        c_ij = (ni, nj) in conn_set\n"
        "        c_ji = (nj, ni) in conn_set\n"
        "        if c_ij and c_ji:\n"
        "            ctype = 'bidirectional'\n"
        "        elif c_ij or c_ji:\n"
        "            ctype = 'unidirectional'\n"
        "        else:\n"
        "            ctype = 'none'\n"
        "        n_ij = syn_n.get((ni, nj), 0)\n"
        "        n_ji = syn_n.get((nj, ni), 0)\n"
        "        max_n   = max(n_ij, n_ji) if (c_ij or c_ji) else np.nan\n"
        "        total_n = (n_ij + n_ji) if (c_ij or c_ji) else np.nan\n"
        "        dist = np.sqrt((xs[i]-xs[j])**2 + (ys[i]-ys[j])**2 + (zs[i]-zs[j])**2)\n"
        "        ori_sim = np.cos(2 * np.deg2rad(thetas[i] - thetas[j]))\n"
        "        rows.append({'ni': ni, 'nj': nj,\n"
        "                     'f_corr': fij,\n"
        "                     'conn_type': ctype,\n"
        "                     'connected': ctype != 'none',\n"
        "                     'n_ij': n_ij, 'n_ji': n_ji,\n"
        "                     'n_synapses': max_n,\n"
        "                     'total_synapses': total_n,\n"
        "                     'dist_um': dist,\n"
        "                     'ori_sim': ori_sim})\n\n"
        "pairs = pd.DataFrame(rows)\n"
        "print(f'Total pairs:         {len(pairs):,}')\n"
        "print(f'Connected pairs:     {pairs[\"connected\"].sum():,}')\n"
        "print(f'  unidirectional:    {(pairs[\"conn_type\"]==\"unidirectional\").sum():,}')\n"
        "print(f'  bidirectional:     {(pairs[\"conn_type\"]==\"bidirectional\").sum():,}')\n"
        "print(f'Unconnected pairs:   {(~pairs[\"connected\"]).sum():,}')\n"
        "print(f'\\nFunctional correlation stats (all pairs):')\n"
        "print(f'  mean={pairs[\"f_corr\"].mean():.4f}  std={pairs[\"f_corr\"].std():.4f}  '\n"
        "      f'min={pairs[\"f_corr\"].min():.4f}  max={pairs[\"f_corr\"].max():.4f}')"
    ),
    cell_md(
        "---\n## Analysis 1 — Functional Correlation Distribution\n\n"
        "Baseline look at what the correlation values look like across all pairs."
    ),
    cell_code(
        "fig, axes = plt.subplots(1, 3, figsize=(16, 4))\n\n"
        "off_diag = F[~np.eye(F.shape[0], dtype=bool)].ravel()\n\n"
        "axes[0].hist(off_diag, bins=60, color='steelblue', edgecolor='white', alpha=0.85)\n"
        "axes[0].axvline(off_diag.mean(), color='navy', lw=2, ls='--',\n"
        "               label=f'mean={off_diag.mean():.3f}')\n"
        "axes[0].axvline(np.median(off_diag), color='tomato', lw=2, ls='--',\n"
        "               label=f'median={np.median(off_diag):.3f}')\n"
        "axes[0].set_xlabel('Pearson correlation')\n"
        "axes[0].set_ylabel('Count')\n"
        "axes[0].set_title('All pairwise correlations')\n"
        "axes[0].legend(fontsize=9)\n\n"
        "order = merged['pref_ori'].argsort().values\n"
        "F_sorted = F[np.ix_(order, order)]\n"
        "im = axes[1].imshow(F_sorted, cmap='RdBu_r', vmin=-0.05, vmax=0.15, aspect='auto')\n"
        "plt.colorbar(im, ax=axes[1], shrink=0.8)\n"
        "axes[1].set_title('Correlation matrix\\n(neurons sorted by pref. ori.)')\n"
        "axes[1].set_xlabel('Neuron index (sorted)')\n"
        "axes[1].set_ylabel('Neuron index (sorted)')\n\n"
        "vals = np.sort(off_diag)\n"
        "axes[2].plot(vals, np.linspace(0, 1, len(vals)), color='steelblue', lw=2)\n"
        "axes[2].axvline(0, color='gray', ls='--', alpha=0.5, label='r=0')\n"
        "axes[2].axvline(0.2, color='orange', ls='--', alpha=0.7, label='r=0.2')\n"
        "axes[2].set_xlabel('Pearson correlation')\n"
        "axes[2].set_ylabel('Cumulative fraction')\n"
        "axes[2].set_title('CDF of pairwise correlations')\n"
        "axes[2].legend(fontsize=9)\n\n"
        "plt.suptitle('Functional Correlation Overview — Session 9.3 V1 (93 neurons)', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        "print(f'Pairs with r > 0.2:  {(off_diag > 0.2).sum():,} / {len(off_diag):,} '\n"
        "      f'({100*(off_diag>0.2).mean():.1f}%)')\n"
        "print(f'Pairs with r > 0:    {(off_diag > 0).sum():,} / {len(off_diag):,} '\n"
        "      f'({100*(off_diag>0).mean():.1f}%)')"
    ),
    cell_md(
        "---\n## Analysis 2 — Connected vs Unconnected Pairs\n\n"
        "Core question: **are neurons that share at least one synapse more functionally correlated?**\n\n"
        "We compare correlations for: unconnected, unidirectional (one direction has synapses), and "
        "bidirectional (both A→B and B→A have synapses) pairs."
    ),
    cell_code(
        "conn_none  = pairs[pairs['conn_type'] == 'none']['f_corr'].values\n"
        "conn_uni   = pairs[pairs['conn_type'] == 'unidirectional']['f_corr'].values\n"
        "conn_bi    = pairs[pairs['conn_type'] == 'bidirectional']['f_corr'].values\n\n"
        "fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
        "data_v   = [conn_none, conn_uni, conn_bi]\n"
        "labels_v = ['Unconnected\\n(n={:,})'.format(len(conn_none)),\n"
        "            'Unidirectional\\n(n={:,})'.format(len(conn_uni)),\n"
        "            'Bidirectional\\n(n={:,})'.format(len(conn_bi))]\n"
        "colors_v = ['#aab7c4', '#4E79A7', '#E15759']\n"
        "parts = axes[0].violinplot(data_v, positions=[1, 2, 3], showmedians=True, showextrema=False)\n"
        "for i, pc in enumerate(parts['bodies']):\n"
        "    pc.set_facecolor(colors_v[i])\n"
        "    pc.set_alpha(0.75)\n"
        "parts['cmedians'].set_color('black')\n"
        "for i, (d, c) in enumerate(zip(data_v, colors_v)):\n"
        "    jitter = np.random.RandomState(i).uniform(-0.15, 0.15, len(d))\n"
        "    axes[0].scatter(np.full(len(d), i+1) + jitter, d,\n"
        "                   alpha=0.25, s=8, color=c, zorder=3)\n"
        "axes[0].set_xticks([1, 2, 3])\n"
        "axes[0].set_xticklabels(labels_v, fontsize=9)\n"
        "axes[0].set_ylabel('Pearson correlation')\n"
        "axes[0].set_title('Functional correlation\\nby connection type')\n\n"
        "bins = np.linspace(-0.05, 0.25, 40)\n"
        "for d, c, lbl in zip(data_v, colors_v, ['Unconnected', 'Unidirectional', 'Bidirectional']):\n"
        "    axes[1].hist(d, bins=bins, density=True, alpha=0.55, color=c,\n"
        "                edgecolor='white', label=f'{lbl} (mean={d.mean():.3f})')\n"
        "axes[1].set_xlabel('Pearson correlation')\n"
        "axes[1].set_ylabel('Density')\n"
        "axes[1].set_title('Distribution by connection type')\n"
        "axes[1].legend(fontsize=8)\n\n"
        "stat_uni,  p_uni  = stats.mannwhitneyu(conn_uni,  conn_none, alternative='greater')\n"
        "stat_bi,   p_bi   = stats.mannwhitneyu(conn_bi,   conn_none, alternative='greater')\n"
        "stat_bivu, p_bivu = stats.mannwhitneyu(conn_bi,   conn_uni,  alternative='greater')\n\n"
        "def cohen_d(a, b):\n"
        "    na, nb = len(a), len(b)\n"
        "    pool = np.sqrt(((na-1)*a.std()**2 + (nb-1)*b.std()**2) / (na+nb-2))\n"
        "    return (a.mean() - b.mean()) / pool\n\n"
        "d_uni  = cohen_d(conn_uni,  conn_none)\n"
        "d_bi   = cohen_d(conn_bi,   conn_none)\n\n"
        "results = {\n"
        "    'Comparison': ['Unidirect. vs Unconn.', 'Bidirect. vs Unconn.',\n"
        "                   'Bidirect. vs Unidirect.'],\n"
        "    'Mean diff': [conn_uni.mean()-conn_none.mean(),\n"
        "                  conn_bi.mean()-conn_none.mean(),\n"
        "                  conn_bi.mean()-conn_uni.mean()],\n"
        "    'Mann-Whitney p': [p_uni, p_bi, p_bivu],\n"
        "    \"Cohen's d\": [d_uni, d_bi, np.nan],\n"
        "}\n"
        "res_df = pd.DataFrame(results)\n"
        "res_df['Mean diff'] = res_df['Mean diff'].map('{:.4f}'.format)\n"
        "res_df['Mann-Whitney p'] = res_df['Mann-Whitney p'].map('{:.4f}'.format)\n"
        "res_df[\"Cohen's d\"] = res_df[\"Cohen's d\"].map(lambda x: f'{x:.3f}' if not np.isnan(x) else 'N/A')\n\n"
        "axes[2].axis('off')\n"
        "tbl = axes[2].table(cellText=res_df.values, colLabels=res_df.columns,\n"
        "                     cellLoc='center', loc='center')\n"
        "tbl.auto_set_font_size(False)\n"
        "tbl.set_fontsize(9)\n"
        "tbl.scale(1.2, 2.0)\n"
        "axes[2].set_title('Statistical tests\\n(one-sided: connected > unconnected)', pad=20)\n\n"
        "plt.suptitle('Analysis 2: Are Directly Connected Neurons More Correlated?', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        "print('\\nMean correlations:')\n"
        "print(f'  Unconnected:    {conn_none.mean():.4f} ± {conn_none.std():.4f}')\n"
        "print(f'  Unidirectional: {conn_uni.mean():.4f} ± {conn_uni.std():.4f}')\n"
        "print(f'  Bidirectional:  {conn_bi.mean():.4f} ± {conn_bi.std():.4f}')\n"
        "print(f'\\nMann-Whitney (unidirectional > unconnected): p={p_uni:.4f}, d={d_uni:.3f}')\n"
        "print(f'Mann-Whitney (bidirectional > unconnected):  p={p_bi:.4f}, d={d_bi:.3f}')"
    ),
    cell_md(
        "---\n## Analysis 3 — Number of Synapses vs Functional Correlation\n\n"
        "Among connected pairs: does a **larger synapse count** predict stronger functional "
        "correlation? Two views: per-direction max (`n_synapses`) and total across both "
        "directions (`total_synapses`)."
    ),
    cell_code(
        "connected_pairs_df = pairs[pairs['connected']].copy()\n\n"
        "fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
        "ax = axes[0]\n"
        "sc = ax.scatter(connected_pairs_df['n_synapses'], connected_pairs_df['f_corr'],\n"
        "               alpha=0.6, s=35, c=connected_pairs_df['f_corr'],\n"
        "               cmap='RdYlGn', edgecolor='none')\n"
        "plt.colorbar(sc, ax=ax, label='Pearson r')\n"
        "r, p = stats.spearmanr(connected_pairs_df['n_synapses'], connected_pairs_df['f_corr'],\n"
        "                        nan_policy='omit')\n"
        "ax.set_xlabel('# synapses (max across directions)')\n"
        "ax.set_ylabel('Functional correlation (Pearson r)')\n"
        "ax.set_title(f'# synapses vs correlation\\nSpearman r={r:.3f}, p={p:.3f}')\n"
        "ax.axhline(0, color='gray', ls='--', alpha=0.4)\n\n"
        "ax2 = axes[1]\n"
        "ax2.scatter(connected_pairs_df['total_synapses'], connected_pairs_df['f_corr'],\n"
        "           alpha=0.6, s=35, color='steelblue', edgecolor='none')\n"
        "r2, p2 = stats.spearmanr(connected_pairs_df['total_synapses'], connected_pairs_df['f_corr'],\n"
        "                          nan_policy='omit')\n"
        "x_ = connected_pairs_df['total_synapses'].astype(float).values\n"
        "y_ = connected_pairs_df['f_corr'].values\n"
        "m, b = np.polyfit(x_, y_, 1)\n"
        "xs_ = np.linspace(x_.min(), x_.max(), 100)\n"
        "ax2.plot(xs_, m*xs_+b, 'tomato', lw=2, label=f'slope={m:.4f}')\n"
        "ax2.set_xlabel('Total # synapses (i→j + j→i)')\n"
        "ax2.set_ylabel('Functional correlation (Pearson r)')\n"
        "ax2.set_title(f'Total # synapses vs correlation\\nSpearman r={r2:.3f}, p={p2:.3f}')\n"
        "ax2.axhline(0, color='gray', ls='--', alpha=0.4)\n"
        "ax2.legend(fontsize=9)\n\n"
        "ax3 = axes[2]\n"
        "cp = connected_pairs_df.dropna(subset=['n_synapses']).copy()\n"
        "# Bin by integer synapse count where possible (counts are small integers).\n"
        "max_n = int(cp['n_synapses'].max())\n"
        "if max_n <= 6:\n"
        "    cp['n_bin'] = cp['n_synapses'].astype(int).astype(str)\n"
        "    bin_order = sorted(cp['n_bin'].unique(), key=int)\n"
        "    q_means = cp.groupby('n_bin', observed=False)['f_corr'].agg(['mean', 'sem']).reindex(bin_order)\n"
        "    xlabel = '# synapses (max direction)'\n"
        "else:\n"
        "    cp['n_bin'] = pd.qcut(cp['n_synapses'], 4,\n"
        "                          labels=['Q1\\n(fewest)', 'Q2', 'Q3', 'Q4\\n(most)'],\n"
        "                          duplicates='drop')\n"
        "    q_means = cp.groupby('n_bin', observed=False)['f_corr'].agg(['mean', 'sem'])\n"
        "    xlabel = '# synapses quartile'\n"
        "ax3.bar(range(len(q_means)), q_means['mean'], yerr=q_means['sem'],\n"
        "       color='steelblue', alpha=0.8, capsize=5, edgecolor='white')\n"
        "ax3.set_xticks(range(len(q_means)))\n"
        "ax3.set_xticklabels(q_means.index.tolist(), fontsize=9)\n"
        "ax3.set_xlabel(xlabel)\n"
        "ax3.set_ylabel('Mean functional correlation')\n"
        "ax3.set_title('Mean correlation by\\n# synapses (±SEM)')\n"
        "ax3.axhline(conn_none.mean(), color='gray', ls='--', alpha=0.6, label='unconnected mean')\n"
        "ax3.legend(fontsize=8)\n\n"
        "plt.suptitle('Analysis 3: Number of Synapses vs Functional Correlation', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    cell_md(
        "---\n## Analysis 4 — Orientation Tuning Similarity vs Structure\n\n"
        "Do structurally connected neurons share preferred orientation?\n"
        "`ori_sim = cos(2·Δθ)` — ranges from -1 (orthogonal) to +1 (same tuning).\n"
        "We ask: (1) are connected pairs more similarly tuned than unconnected ones? "
        "(2) does tuning similarity predict functional correlation?"
    ),
    cell_code(
        "fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
        "d_none = pairs[pairs['conn_type']=='none']['ori_sim'].values\n"
        "d_uni2 = pairs[pairs['conn_type']=='unidirectional']['ori_sim'].values\n"
        "d_bi2  = pairs[pairs['conn_type']=='bidirectional']['ori_sim'].values\n"
        "data_o = [d_none, d_uni2, d_bi2]\n"
        "labels_o = ['Unconn.\\n(n={:,})'.format(len(d_none)),\n"
        "            'Unidir.\\n(n={:,})'.format(len(d_uni2)),\n"
        "            'Bidir.\\n(n={:,})'.format(len(d_bi2))]\n"
        "colors_o = ['#aab7c4', '#4E79A7', '#E15759']\n"
        "parts = axes[0].violinplot(data_o, positions=[1,2,3], showmedians=True, showextrema=False)\n"
        "for i, pc in enumerate(parts['bodies']):\n"
        "    pc.set_facecolor(colors_o[i]); pc.set_alpha(0.75)\n"
        "parts['cmedians'].set_color('black')\n"
        "axes[0].set_xticks([1,2,3])\n"
        "axes[0].set_xticklabels(labels_o, fontsize=9)\n"
        "axes[0].axhline(0, color='gray', ls='--', alpha=0.5)\n"
        "axes[0].set_ylabel('Orientation similarity cos(2Δθ)')\n"
        "axes[0].set_title('Tuning similarity\\nby connection type')\n"
        "s_ori_uni, p_ori_uni = stats.mannwhitneyu(d_uni2, d_none, alternative='greater')\n"
        "s_ori_bi,  p_ori_bi  = stats.mannwhitneyu(d_bi2,  d_none, alternative='greater')\n"
        "axes[0].text(0.5, 0.02, f'Unidir vs unconn: p={p_ori_uni:.3f}\\nBidir vs unconn: p={p_ori_bi:.3f}',\n"
        "            transform=axes[0].transAxes, fontsize=8, ha='center')\n\n"
        "axes[1].scatter(pairs['ori_sim'], pairs['f_corr'],\n"
        "                alpha=0.18, s=8,\n"
        "                c=pairs['connected'].map({True: '#E15759', False: '#aab7c4'}),\n"
        "                edgecolor='none')\n"
        "r_os, p_os = stats.spearmanr(pairs['ori_sim'], pairs['f_corr'])\n"
        "axes[1].set_xlabel('Orientation similarity cos(2Δθ)')\n"
        "axes[1].set_ylabel('Functional correlation (r)')\n"
        "axes[1].set_title(f'Tuning sim vs Functional corr\\nSpearman r={r_os:.3f}, p={p_os:.3e}')\n"
        "axes[1].axhline(0, color='gray', ls='--', alpha=0.3)\n"
        "axes[1].axvline(0, color='gray', ls='--', alpha=0.3)\n"
        "from matplotlib.patches import Patch\n"
        "axes[1].legend(handles=[\n"
        "    Patch(color='#E15759', label='Connected'),\n"
        "    Patch(color='#aab7c4', label='Unconnected')\n"
        "], fontsize=8)\n\n"
        "pairs['dpref'] = np.abs((pairs['ori_sim'].apply(np.arccos) / 2) * 180 / np.pi)\n"
        "bins_d = [0, 22.5, 45, 67.5, 90]\n"
        "pairs['ori_bin'] = pd.cut(pairs['dpref'], bins=bins_d,\n"
        "                          labels=['0-22.5°', '22.5-45°', '45-67.5°', '67.5-90°'])\n"
        "for ctype, col, lbl in [('none', '#aab7c4', 'Unconnected'),\n"
        "                         ('unidirectional', '#4E79A7', 'Unidirect.'),\n"
        "                         ('bidirectional', '#E15759', 'Bidirect.')]:\n"
        "    grp = pairs[pairs['conn_type']==ctype].groupby('ori_bin', observed=False)['f_corr'].mean()\n"
        "    axes[2].plot(range(len(grp)), grp.values, marker='o', color=col, label=lbl, lw=2)\n"
        "axes[2].set_xticks(range(4))\n"
        "axes[2].set_xticklabels(['0-22.5°', '22.5-45°', '45-67.5°', '67.5-90°'], fontsize=9)\n"
        "axes[2].set_xlabel('|Δpreferred orientation|')\n"
        "axes[2].set_ylabel('Mean functional correlation')\n"
        "axes[2].set_title('Functional corr vs tuning difference\\nby connection type')\n"
        "axes[2].legend(fontsize=8)\n\n"
        "plt.suptitle('Analysis 4: Orientation Tuning Similarity vs Structure', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    cell_md(
        "---\n## Analysis 5 — Hub Neurons: Structural vs Functional Centrality\n\n"
        "Are the neurons with the most synapses also the most correlated neurons overall?\n"
        "Per-neuron mean functional correlation vs structural degree (# partners) and "
        "strength (total # synapses)."
    ),
    cell_code(
        "merged['mean_f_corr'] = [\n"
        "    float(np.mean(np.delete(F[mi, :], mi)))\n"
        "    for mi in merged['matrix_index']\n"
        "]\n"
        "merged['total_degree']   = merged['out_degree'] + merged['in_degree']\n"
        "merged['total_strength'] = merged['out_strength'] + merged['in_strength']\n\n"
        "fig, axes = plt.subplots(2, 3, figsize=(17, 10))\n\n"
        "def scatter_with_r(ax, x, y, xlabel, ylabel, title, color='steelblue'):\n"
        "    ax.scatter(x, y, alpha=0.65, s=50, color=color, edgecolor='white', lw=0.5)\n"
        "    r, p = stats.spearmanr(x, y, nan_policy='omit')\n"
        "    m2, b2 = np.polyfit(x, y, 1)\n"
        "    xs2 = np.linspace(x.min(), x.max(), 100)\n"
        "    ax.plot(xs2, m2*xs2+b2, 'tomato', lw=1.8)\n"
        "    ax.set_xlabel(xlabel); ax.set_ylabel(ylabel)\n"
        "    ax.set_title(f'{title}\\nSpearman r={r:.3f}, p={p:.3f}')\n\n"
        "scatter_with_r(axes[0,0],\n"
        "    merged['total_degree'].values.astype(float),\n"
        "    merged['mean_f_corr'].values,\n"
        "    'Total degree (# partners, in+out)',\n"
        "    'Mean functional correlation',\n"
        "    'Degree vs Functional centrality')\n\n"
        "scatter_with_r(axes[0,1],\n"
        "    merged['total_strength'].values.astype(float),\n"
        "    merged['mean_f_corr'].values,\n"
        "    'Total # synapses (in+out)',\n"
        "    'Mean functional correlation',\n"
        "    '# Synapses vs Functional centrality')\n\n"
        "scatter_with_r(axes[0,2],\n"
        "    merged['out_degree'].values.astype(float),\n"
        "    merged['mean_f_corr'].values,\n"
        "    'Out-degree (# targets)',\n"
        "    'Mean functional correlation',\n"
        "    'Out-degree vs Functional centrality',\n"
        "    color='#59A14F')\n\n"
        "scatter_with_r(axes[1,0],\n"
        "    merged['in_degree'].values.astype(float),\n"
        "    merged['mean_f_corr'].values,\n"
        "    'In-degree (# inputs)',\n"
        "    'Mean functional correlation',\n"
        "    'In-degree vs Functional centrality',\n"
        "    color='#F28E2B')\n\n"
        "scatter_with_r(axes[1,1],\n"
        "    merged['gOSI'].values,\n"
        "    merged['mean_f_corr'].values,\n"
        "    'gOSI (orientation selectivity)',\n"
        "    'Mean functional correlation',\n"
        "    'Selectivity vs Functional centrality',\n"
        "    color='#B07AA1')\n\n"
        "scatter_with_r(axes[1,2],\n"
        "    merged['cc_abs'].values,\n"
        "    merged['mean_f_corr'].values,\n"
        "    'cc_abs (Digital Twin fit quality)',\n"
        "    'Mean functional correlation',\n"
        "    'Fit quality vs Functional centrality',\n"
        "    color='#E15759')\n\n"
        "plt.suptitle('Analysis 5: Per-Neuron Structural vs Functional Properties', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),
    cell_md(
        "---\n## Analysis 6 — Spatial Distance Effects\n\n"
        "Do nearby neurons have stronger functional correlations?\n"
        "Are nearby neurons more likely to be synaptically connected?"
    ),
    cell_code(
        "fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
        "ax = axes[0]\n"
        "ax.scatter(pairs[~pairs['connected']]['dist_um'],\n"
        "           pairs[~pairs['connected']]['f_corr'],\n"
        "           alpha=0.12, s=6, color='#aab7c4', label='Unconnected')\n"
        "ax.scatter(pairs[pairs['connected']]['dist_um'],\n"
        "           pairs[pairs['connected']]['f_corr'],\n"
        "           alpha=0.6, s=25, color='#E15759', label='Connected', zorder=5)\n"
        "r_df, p_df = stats.spearmanr(pairs['dist_um'], pairs['f_corr'])\n"
        "ax.set_xlabel('3D distance (µm)')\n"
        "ax.set_ylabel('Functional correlation (r)')\n"
        "ax.set_title(f'Distance vs Functional corr\\nSpearman r={r_df:.3f}, p={p_df:.3f}')\n"
        "ax.legend(fontsize=8)\n\n"
        "ax2 = axes[1]\n"
        "pairs['dist_bin'] = pd.qcut(pairs['dist_um'], 5,\n"
        "                             labels=['Q1\\n(closest)', 'Q2', 'Q3', 'Q4', 'Q5\\n(farthest)'])\n"
        "for ctype, col, lbl in [('none', '#aab7c4', 'Unconnected'),\n"
        "                         ('unidirectional', '#4E79A7', 'Unidirect.'),\n"
        "                         ('bidirectional', '#E15759', 'Bidirect.')]:\n"
        "    sub = pairs[pairs['conn_type']==ctype].groupby('dist_bin', observed=False)['f_corr'].mean()\n"
        "    if len(sub.dropna()) > 0:\n"
        "        ax2.plot(range(len(sub)), sub.values, marker='o', color=col, label=lbl, lw=2)\n"
        "ax2.set_xticks(range(5))\n"
        "ax2.set_xticklabels(['Q1\\n(closest)', 'Q2', 'Q3', 'Q4', 'Q5\\n(farthest)'], fontsize=8)\n"
        "ax2.set_xlabel('Distance quintile')\n"
        "ax2.set_ylabel('Mean functional correlation')\n"
        "ax2.set_title('Functional corr vs distance bin\\nby connection type')\n"
        "ax2.legend(fontsize=8)\n\n"
        "ax3 = axes[2]\n"
        "dist_bins = np.linspace(0, pairs['dist_um'].max(), 40)\n"
        "ax3.hist(pairs[~pairs['connected']]['dist_um'], bins=dist_bins,\n"
        "        density=True, alpha=0.55, color='#aab7c4', label='Unconnected', edgecolor='white')\n"
        "ax3.hist(pairs[pairs['connected']]['dist_um'], bins=dist_bins,\n"
        "        density=True, alpha=0.75, color='#E15759', label='Connected', edgecolor='white')\n"
        "stat_d, p_d = stats.mannwhitneyu(\n"
        "    pairs[pairs['connected']]['dist_um'],\n"
        "    pairs[~pairs['connected']]['dist_um'])\n"
        "ax3.set_xlabel('3D distance (µm)')\n"
        "ax3.set_ylabel('Density')\n"
        "ax3.set_title(f'Distance distribution\\nMW p={p_d:.4f} (conn vs unconn)')\n"
        "ax3.legend(fontsize=8)\n\n"
        "plt.suptitle('Analysis 6: Spatial Distance Effects', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        "print(f'Mean distance (connected):   {pairs[pairs[\"connected\"]][\"dist_um\"].mean():.1f} µm')\n"
        "print(f'Mean distance (unconnected): {pairs[~pairs[\"connected\"]][\"dist_um\"].mean():.1f} µm')"
    ),
    cell_md(
        "---\n## Analysis 7 — Network Topology Comparison\n\n"
        "Build a **functional network** by thresholding the correlation matrix at the same "
        "edge density as the structural 93-neuron count network, then compare topology."
    ),
    cell_code(
        "N = 93\n"
        "n_struct_edges = len(s_edges)\n"
        "struct_density = n_struct_edges / (N * (N - 1))\n"
        "print(f'Structural density (93-neuron, count-weighted): {struct_density:.4f}')\n"
        "print(f'Structural edges: {n_struct_edges}')\n\n"
        "n_func_edges_target = n_struct_edges\n"
        "off_diag_pairs = [(i, j, F[i, j])\n"
        "                  for i in range(N) for j in range(N) if i != j]\n"
        "off_diag_pairs.sort(key=lambda x: -x[2])\n"
        "top_pairs = off_diag_pairs[:n_func_edges_target]\n\n"
        "G_struct = nx.from_pandas_edgelist(\n"
        "    s_edges, 'pre_neuron_id', 'post_neuron_id',\n"
        "    edge_attr='n_synapses', create_using=nx.DiGraph())\n"
        "G_struct.add_nodes_from(s_nodes['neuron_id'].astype('int64').tolist())\n\n"
        "midx_to_id = {v: k for k, v in id2midx.items()}\n"
        "G_func = nx.DiGraph()\n"
        "G_func.add_nodes_from(neurons)\n"
        "for (i, j, w) in top_pairs:\n"
        "    G_func.add_edge(midx_to_id[i], midx_to_id[j], weight=w)\n\n"
        "print(f'Functional network (density-matched): {G_func.number_of_nodes()} nodes, {G_func.number_of_edges()} edges')\n\n"
        "fig, axes = plt.subplots(1, 3, figsize=(17, 5))\n\n"
        "deg_s = [d for _, d in G_struct.degree()]\n"
        "deg_f = [d for _, d in G_func.degree()]\n"
        "bins_deg = np.linspace(0, max(max(deg_s), max(deg_f)) + 1, 25)\n"
        "axes[0].hist(deg_s, bins=bins_deg, alpha=0.65, color='tomato',\n"
        "            edgecolor='white', label=f'Structural (mean={np.mean(deg_s):.1f})')\n"
        "axes[0].hist(deg_f, bins=bins_deg, alpha=0.65, color='steelblue',\n"
        "            edgecolor='white', label=f'Functional (mean={np.mean(deg_f):.1f})')\n"
        "axes[0].set_xlabel('Total degree (in+out)')\n"
        "axes[0].set_ylabel('Count')\n"
        "axes[0].set_title('Degree distribution\\nStructural vs Functional')\n"
        "axes[0].legend(fontsize=9)\n\n"
        "deg_s_dict = dict(G_struct.degree())\n"
        "deg_f_dict = dict(G_func.degree())\n"
        "common = [n for n in G_struct.nodes() if n in deg_f_dict]\n"
        "ds = np.array([deg_s_dict[n] for n in common])\n"
        "df2 = np.array([deg_f_dict[n] for n in common])\n"
        "r_dd, p_dd = stats.spearmanr(ds, df2)\n"
        "axes[1].scatter(ds, df2, alpha=0.65, s=45, color='#59A14F', edgecolor='white', lw=0.5)\n"
        "m3, b3 = np.polyfit(ds, df2, 1)\n"
        "xs3 = np.linspace(ds.min(), ds.max(), 100)\n"
        "axes[1].plot(xs3, m3*xs3+b3, 'tomato', lw=1.8)\n"
        "axes[1].set_xlabel('Structural degree')\n"
        "axes[1].set_ylabel('Functional degree')\n"
        "axes[1].set_title(f'Are hub neurons the same?\\nSpearman r={r_dd:.3f}, p={p_dd:.3f}')\n\n"
        "def topo_stats(G, label):\n"
        "    G_un = G.to_undirected()\n"
        "    n_edges = G.number_of_edges()\n"
        "    density = nx.density(G)\n"
        "    ccs = list(nx.weakly_connected_components(G)) if G.is_directed() else list(nx.connected_components(G))\n"
        "    giant = max(ccs, key=len) if ccs else set()\n"
        "    G_giant = G.subgraph(giant)\n"
        "    try:\n"
        "        apl = nx.average_shortest_path_length(G_giant.to_undirected())\n"
        "    except Exception:\n"
        "        apl = float('nan')\n"
        "    cc_ = nx.average_clustering(G_un)\n"
        "    return {'Network': label, 'Nodes': G.number_of_nodes(),\n"
        "            'Edges': n_edges, 'Density': f'{density:.4f}',\n"
        "            'Avg clustering': f'{cc_:.3f}',\n"
        "            'Avg path length': f'{apl:.3f}' if not np.isnan(apl) else 'N/A',\n"
        "            'Giant component': len(giant)}\n\n"
        "rows_t = [topo_stats(G_struct, 'Structural (93)'),\n"
        "          topo_stats(G_func,   'Functional (93, density-matched)')]\n"
        "topo_df = pd.DataFrame(rows_t)\n"
        "axes[2].axis('off')\n"
        "tbl2 = axes[2].table(cellText=topo_df.T.values,\n"
        "                      rowLabels=topo_df.columns,\n"
        "                      colLabels=['Structural', 'Functional'],\n"
        "                      cellLoc='center', loc='center')\n"
        "tbl2.auto_set_font_size(False)\n"
        "tbl2.set_fontsize(9)\n"
        "tbl2.scale(1.2, 1.9)\n"
        "axes[2].set_title('Topology comparison', pad=20)\n\n"
        "plt.suptitle('Analysis 7: Network Topology — Structural vs Functional (93 neurons)', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        "print(topo_df.to_string(index=False))"
    ),
    cell_md(
        "---\n## Analysis 8 — Reciprocal (Bidirectional) Connections\n\n"
        "How many neuron pairs are bidirectionally connected (A→B and B→A)?\n"
        "Are they more correlated? Are they more similar in orientation tuning?"
    ),
    cell_code(
        "bidir_pairs = pairs[pairs['conn_type'] == 'bidirectional']\n"
        "unidir_pairs = pairs[pairs['conn_type'] == 'unidirectional']\n"
        "unconn_pairs = pairs[pairs['conn_type'] == 'none']\n\n"
        "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n\n"
        "groups = ['Unconnected', 'Unidirect.', 'Bidirect.']\n"
        "corr_means = [unconn_pairs['f_corr'].mean(),\n"
        "              unidir_pairs['f_corr'].mean(),\n"
        "              bidir_pairs['f_corr'].mean()]\n"
        "corr_sems  = [stats.sem(unconn_pairs['f_corr']),\n"
        "              stats.sem(unidir_pairs['f_corr']),\n"
        "              stats.sem(bidir_pairs['f_corr'])]\n"
        "bars = axes[0].bar(groups, corr_means, yerr=corr_sems,\n"
        "                   color=['#aab7c4', '#4E79A7', '#E15759'],\n"
        "                   alpha=0.85, capsize=6, edgecolor='white')\n"
        "axes[0].set_ylabel('Mean functional correlation (±SEM)')\n"
        "axes[0].set_title('Functional correlation by\\nconnection type')\n"
        "for bar, val in zip(bars, corr_means):\n"
        "    axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.0005,\n"
        "               f'{val:.4f}', ha='center', va='bottom', fontsize=9)\n\n"
        "ori_means = [unconn_pairs['ori_sim'].mean(),\n"
        "             unidir_pairs['ori_sim'].mean(),\n"
        "             bidir_pairs['ori_sim'].mean()]\n"
        "ori_sems  = [stats.sem(unconn_pairs['ori_sim']),\n"
        "             stats.sem(unidir_pairs['ori_sim']),\n"
        "             stats.sem(bidir_pairs['ori_sim'])]\n"
        "bars2 = axes[1].bar(groups, ori_means, yerr=ori_sems,\n"
        "                    color=['#aab7c4', '#4E79A7', '#E15759'],\n"
        "                    alpha=0.85, capsize=6, edgecolor='white')\n"
        "axes[1].set_ylabel('Mean orientation similarity cos(2Δθ) (±SEM)')\n"
        "axes[1].set_title('Orientation tuning similarity by\\nconnection type')\n"
        "for bar, val in zip(bars2, ori_means):\n"
        "    axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.001,\n"
        "               f'{val:.3f}', ha='center', va='bottom', fontsize=9)\n\n"
        "plt.suptitle('Analysis 8: Reciprocal Connections', fontweight='bold')\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        "print(f'Bidirectional pairs: {len(bidir_pairs)}')\n"
        "print(f'Fraction of connected pairs that are bidirectional: '\n"
        "      f'{len(bidir_pairs)/max(len(bidir_pairs)+len(unidir_pairs),1):.3f}')"
    ),
    cell_md(
        "---\n## Summary\n\n"
        "| Analysis | Finding |\n"
        "|----------|---------|\n"
        "| Connected vs unconnected | Fill in after running |\n"
        "| # synapses vs correlation | Fill in after running |\n"
        "| Orientation tuning | Fill in after running |\n"
        "| Hub neurons | Fill in after running |\n"
        "| Spatial distance | Fill in after running |\n"
        "| Network topology | Fill in after running |\n"
        "| Reciprocal connections | Fill in after running |"
    ),
]

write_nb(OUT / "compare_structural_functional-Leo.ipynb", c_cells)

print("\nAll three notebooks written.")
